---
title: "REU_Project_Overview"
output: html_document
author: "Andrew Mercadante"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Preliminary thoughts on introduction/hypotheses to test

Due to anthropogenic activities such as ____ and _____, landscapes worldwide have become more spatially complex (). The clearing and converting of once-continuous habitats splits them into distinct patches separated from the surrounding activities by often abrubpt edges or boundaries. Investigating the nuances of patch-boundary interactions is a paramount objective of ecologists; patch-boundary interactions influence distribution patterns of resources, species, and they can alter the magnitude and direction of ecological flows, which can have massive implications for an ecosystem's functionality (). For example, boundary structure, the arrangement of physical and biological features in three-dimensional space, is a boundary characteristic that predicts whether a boundary is neutral, inhibitory, or faciliatory to ecological flows between two neighboring patches (Cadenosso et al. 2003) <!--# ERS: this seems like a useful definition, but I was expecting an example of changes in ecosystem function near edges.-->.

Edge effects, a form of patch-boundary interaction, have become a topic of interest for ecologists and conservationists, as edges are the dominant boundary-type in fragmented landscapes. Edge effects are always defined relative to a specific response variable, with edge effects being measured by determining how a response variable changes at varying distances from an edge. Edge effects have been shown to impact species distribution and species interactions like pollination, dispersal, and predation (). Quantifying edge effects permits ecologists to better understand how fragmented landscapes will affect different species, while providing conservationists with well-informed models to predict species-specific and community-level responses to ongoing fragmentation. For example, as a landscape becomes progressively fragmented, average patch size typically decreases, which means edge effects penetrate further into these patches. If an edge effects' depth of influence increases, then the area unaffected by edge effects or "core area" will diminish or be eliminated if the patch is too small (). Patches below a critical size threshold may be unable to support edge-sensitive species, resulting in shifts in community biodiversity (). Additionally, some species exhibit edge avoidance or can be adversely affected by environmental stressors induced by edge-associated microclimates, which is a potential explanation for temporal and spatial shifts in species distributions, and the course, emergent patterns unique to fragmented landscapes ().

The magnitude and depth of influence of edge effects are dictated largely by edge permeability and edge contrast with adjoining patches (). Less understood is how edge effects are impacted by the interaction of nearby edges. Edge interactions show promise in explaining landscape-level variations in species distributions due to regional changes in spatial complexity (e.g., number of interacting edges) ().

Using data obtained on populations of *Heliconia acuminata* located within the experimentally fragmented rainforest of the BDFFP, we will quantify the spatial extent and magnitude of the edge effects for 1-ha fragments using vocabulary consistent with the conceptual framework outlined by Porensky and Young (2013). In particular, these data provide a unique opportunity to determine if demographic edge effects are compounded by proximity to multiple edges. We predict that as plant proximity to the forest edge increases (1) the annual growth rate of *H. acuminata* individuals will decrease, (2), the probability of survival will decrease, and (3) the abundance of *H. acuminata* will decrease. We also predict that (4) the magnitude of edge effects will increase with increasing proxmity to multiple edges.  

Another question to answer would be if plants experiencing edge effects demonstrate greater year-to-year variance in their measured response variables. Quantifying variance on important demographic parameters could be relevant to smaller populations, as increased variance in vital rates of a small population can dramatically increase extinction risk ().

<!--# ERS: I like the idea of looking for edge effects on abundance/density, but I'm not sure about the methods for doing that. I encourage you to explore that on your own if you're interested, but I'm not sure how much I can help with that particular question. 

Things we do have data for that I think are important to test:
- What is the depth and magnitude of edge effects on different vital rates in fragments?
- Are there edge interactions? (i.e. effects of next-nearest edge)
- Does the depth and magnitude of edge effects vary by year? 

As a bonus:
- Can year-to-year variation be explained by time since clearing of the matrix? 
- Is year-to-year variation related to drought conditions?
-->

## References
